language: perl
sudo: false
dist: xenial
addons:
  apt:
    packages:
      - libelf-dev
matrix:
   include:
      - perl: '5.28'
        env: KERNEL_VERSION=5.1.1 MODULE_TO_TEST=fs/exportfs
      - perl: '5.26'
        env: KERNEL_VERSION=4.19.42 MODULE_TO_TEST=fs/efivarfs
      - perl: '5.24'
        env: KERNEL_VERSION=4.14.118 MODULE_TO_TEST=fs/tracefs
      - perl: '5.22'
        env: KERNEL_VERSION=4.9.175 MODULE_TO_TEST=fs/ramfs

cache:
  directories:
  - $HOME/perl5
  - linux-$KERNEL_VERSION

before_install:
  cpanm --quiet --notest Devel::Cover::Report::Coveralls Devel::Cover::Report::Kritika

script:
  cover -test

after_success:
  cover -ignore_re=^/ -ignore_re=^t -report coveralls -report kritika
