language: perl
sudo: false
addons:
  apt:
    packages:
      - libelf-dev
matrix:
   include:
      - perl: '5.26'
        env: KERNEL_VERSION=4.16.8 MODULE_TO_TEST=fs/ramfs
      - perl: '5.14'
        env: KERNEL_VERSION=4.1.51 MODULE_TO_TEST=fs/sysfs

cache:
  directories:
  - $HOME/perl5
  - linux-$KERNEL_VERSION

before_install:
  cpanm --quiet --notest Devel::Cover::Report::Coveralls Devel::Cover::Report::Kritika

script:
  cover -test

after_success:
  cover -ignore_re=^/ -ignore_re=^t -report coveralls -report kritika
