language: perl
sudo: false
addons:
  apt:
    packages:
      - libelf-dev
matrix:
   include:
      - perl: '5.26'
        env: KERNEL_VERSION=4.17.3 MODULE_TO_TEST=fs/exportfs
      - perl: '5.24'
        env: KERNEL_VERSION=4.16.18 MODULE_TO_TEST=fs/efivarfs
      - perl: '5.20'
        env: KERNEL_VERSION=4.14.52 MODULE_TO_TEST=fs/tracefs
      - perl: '5.18'
        env: KERNEL_VERSION=4.9.110 MODULE_TO_TEST=fs/ramfs
      - perl: '5.16'
        env: KERNEL_VERSION=4.4.138 MODULE_TO_TEST=fs/sysfs

cache:
  directories:
  - $HOME/perl5
  - linux-$KERNEL_VERSION

before_install:
  cpanm --quiet --notest Devel::Cover::Report::Coveralls Devel::Cover::Report::Kritika

script:
  cover -test

after_success:
  cover -ignore_re=^/ -ignore_re=^t -report coveralls -report kritika
